// Code generated by goctl. DO NOT EDIT!
// Source: chat.proto

package server

import (
	"context"

	"wx-chat/service/chat/cmd/rpc/internal/logic"
	"wx-chat/service/chat/cmd/rpc/internal/svc"
	"wx-chat/service/chat/cmd/rpc/pb"
)

type ChatCenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatCenterServer
}

func NewChatCenterServer(svcCtx *svc.ServiceContext) *ChatCenterServer {
	return &ChatCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatCenterServer) GetChatList(ctx context.Context, in *pb.ChatListReq) (*pb.ChatListResp, error) {
	l := logic.NewGetChatListLogic(ctx, s.svcCtx)
	return l.GetChatList(in)
}
