// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chat "wx-chat/service/chat/cmd/api/internal/handler/chat"
	"wx-chat/service/chat/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/list",
				Handler: chat.ListHandler(serverCtx),
			},
		},
	)
}
