// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}

type RegisterRes struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type FindUserReq struct {
	Name string `form:"name"`
}

type FindUserRes struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Gender   string `json:"gender"`
}
