// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `form:"username"`
	Gender   int64  `form:"gender"`
}

type FindUserReq struct {
	UserId int64 `form:"userId"`
}

type FindUser struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   int64  `json:"gender"`
}

type FindUserRes struct {
	IRet  int64    `json:"iRet"`
	SMsg  string   `json:"sMsg"`
	SData FindUser `json:"sData"`
}

type CommonRes struct {
	IRet int64  `json:"iRet"`
	SMsg string `json:"sMsg"`
}
