// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   int64`json:"gender"`
}

type RegisterRes struct {
	Msg string `json:"msg"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Gender       int64 `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type FindUserReq struct {
	Username string `form:"username"`
}

type FindUserRes struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Gender   int64 `json:"gender"`
}
