// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: chat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatCenterClient is the client API for ChatCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatCenterClient interface {
	GetChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error)
}

type chatCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewChatCenterClient(cc grpc.ClientConnInterface) ChatCenterClient {
	return &chatCenterClient{cc}
}

func (c *chatCenterClient) GetChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error) {
	out := new(ChatListResp)
	err := c.cc.Invoke(ctx, "/pb.ChatCenter/GetChatList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatCenterServer is the server API for ChatCenter service.
// All implementations must embed UnimplementedChatCenterServer
// for forward compatibility
type ChatCenterServer interface {
	GetChatList(context.Context, *ChatListReq) (*ChatListResp, error)
	mustEmbedUnimplementedChatCenterServer()
}

// UnimplementedChatCenterServer must be embedded to have forward compatible implementations.
type UnimplementedChatCenterServer struct {
}

func (UnimplementedChatCenterServer) GetChatList(context.Context, *ChatListReq) (*ChatListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatList not implemented")
}
func (UnimplementedChatCenterServer) mustEmbedUnimplementedChatCenterServer() {}

// UnsafeChatCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatCenterServer will
// result in compilation errors.
type UnsafeChatCenterServer interface {
	mustEmbedUnimplementedChatCenterServer()
}

func RegisterChatCenterServer(s grpc.ServiceRegistrar, srv ChatCenterServer) {
	s.RegisterService(&ChatCenter_ServiceDesc, srv)
}

func _ChatCenter_GetChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCenterServer).GetChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChatCenter/GetChatList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCenterServer).GetChatList(ctx, req.(*ChatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatCenter_ServiceDesc is the grpc.ServiceDesc for ChatCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChatCenter",
	HandlerType: (*ChatCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChatList",
			Handler:    _ChatCenter_GetChatList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
