// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type SearchReq struct {
	Name string `form:"name"`
}

type SearchReply struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Number   string `json:"number"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Number   string `json:"number"`
	Password string `json:"password"`
}

type RegisterRes struct {
	Msg string `json:"msg"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoRes struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
